---
name: Pull Request CI

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'action.yml'
      - '.github/workflows/*.yml'

env:
  DOCKER_IMAGE_NAME: ${{ github.repository }}/molecule

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:test

      - name: Run molecule
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE_NAME }}:test molecule --version
