---
name: Pull Request CI

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'action.yml'
      - '.github/workflows/*.yml'

env:
  DOCKER_IMAGE_NAME: gofrolist/molecule

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test run Molecule
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE_NAME }}:test molecule --version
