---
name: Pull Request CI

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'action.yml'
      - '.github/workflows/*.yml'

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_IMAGE_NAME: ${{ github.repository }}/molecule

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}
          repository: ${{ env.DOCKER_IMAGE_NAME }}
          tag_with_ref: true
          tags: pr-build

      - name: Run molecule
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.DOCKER_REGISTRY }} -u ${{ github.actor }} --password-stdin
          export DOCKER_IMAGE=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:pr-build
          docker pull ${DOCKER_IMAGE}
          docker run ${DOCKER_IMAGE} molecule --version
